### ISSUE TITLE
Allowing multiple ID types and free text to represent the disease in the GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1328]
Currently when creating a GDM, a disease can only be identified by an Orphanet ID. This needs to be opened up to include DO, NCIT and OMIM IDs, and when none of these IDs are available then the curator should be able to add free text instead.

1. In the GDM allow any of the following ID types:
Orphanet
DO
OMIM
NCIt

<img width="1054" alt="screen shot 2017-04-11 at 3 31 38 pm" src="https://cloud.githubusercontent.com/assets/15131169/24933611/0308f364-1ecc-11e7-80cf-08702e32b1e1.png">

2. We currently populate the disease name automatically based on the Orphanet ID entered, this functionality will need to be expanded to include pulling in the disease names based on OMIM, DO and NCIt disease names.

3. If none of the above disease IDs are available then the curator should have the option of clicking a button to add free text. However they must:
i)first enter some sort of confirmation that they have checked all of the ontologies
ii)have option of including phenotypes, so another curator can match to it 

<img width="838" alt="screen shot 2017-04-11 at 3 47 15 pm" src="https://cloud.githubusercontent.com/assets/15131169/24934039/3e7736de-1ece-11e7-86ab-cd63514b558c.png">

4. The curator must have a means of changing the disease once they've entered it

<img width="1071" alt="screen shot 2017-04-11 at 3 59 55 pm" src="https://cloud.githubusercontent.com/assets/15131169/24934363/0810e8e0-1ed0-11e7-8afe-80f522aadf44.png">

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is the instance for you to review the prototype of the modal for users to enter disease information:
https://1328-jz-disease-id-types-043b3aa-jzhen.demo.clinicalgenome.org

There are still quite a few details to be worked out (e.g. free text entry confirmation, HPO id validation).

Most importantly, the disease information CAN NOT be saved into the GDM object at the moment. I will need to discuss with Karen on how the GDM schema shall be changed to deal with the disease property that no longer links to the Orphanet object (with implications on existing GDM data in production).

I look forward to all your feedback on this prototype. Thanks!

**Comment by wrightmw** [comment]
Hi @jimmyzhen 
Wow, you've come so far on this already! Great work!

I'm going to have a play with it. However, two quick things:

Currently I don't feel it's that obvious to the user that the magnifying glass is how they look-up/add disease gene names...it looks like they can just type IDs into the box, but I think we want people to only use the modal to add disease names?
How about greying out the box and having a button on the RHS of the greyed-out box...e.g. re-using the buttons from the VCI:
![screen shot 2017-05-02 at 5 09 40 pm](https://cloud.githubusercontent.com/assets/15131169/25644687/dd221eb8-2f5c-11e7-9636-4e7d6ef8c6f7.png)
![screen shot 2017-05-02 at 5 26 04 pm](https://cloud.githubusercontent.com/assets/15131169/25644690/e0d92b8c-2f5c-11e7-8eda-165573f2c1d0.png)

Once the modal opens, the LHS text in the modal should say something like:

“Select disease source”

Note: the ‘i’ in NCIt should be a capital letter in all instances where you display it

**Comment by selinad** [comment]
Hi @jimmyzhen -- I tested a bit yesterday, and will do more thorough testing this afternoon.  The API is great and I agree with @wrightmw that you implemented this very quickly and it's a fantastic improvement.  Every disease I checked worked perfectly and I love having the descriptions come back.

One quick comment -- it would be great to have the UI for this mimic (as much as possible) the UI for the ClinVar modal, etc.  I think @wrightmw is on the right track with respect to it looking like adding a disease in the VCI, but need to think through a bit more. I'll add some more ideas when visiting it again.

I'm a bit worried about the edit button -- are we going to allow people to edit a disease once evidence has been added to the GDM?

**Comment by wrightmw** [comment]
@selinad 
The edit disease button is vital on the GDM selection page so that curators can go in and edit when they have entered the wrong disease. Once they click through to curation central it's a different story, they would only have the edit disease button when free text has been entered so that they can change it to one of the disease IDs, when available.

**Comment by selinad** [comment]
Ok, perfect -- thx @wrightmw !

**Comment by selinad** [comment]
Hi @jimmyzhen -- here is what we discussed (I know you already have some under development)

Create GDM page:
- Use same + Disease button as in VCI for the Disease entry (per above discussion)
- Add "Search OLS for disease term" directly under the text that says enter disease 

On modal window:
- On top row: "Search OLS for disease term"    "[Orphanet][Disease Ontology][NCIt][OMIM]"
- URLs for different terminology sites
-- Orphanet = http://www.orpha.net/consor/cgi-bin/index.php
-- Disease Ontology = http://disease-ontology.org/
-- NCIt = https://ncit.nci.nih.gov/ncitbrowser/
-- OMIM = http://omim.org/
- prepend ID (e.g. ORPHA15) to disease term and make the term name (not ID) a hyperlink to OLS entry
- include 2 different error messages (error querying OLS vs. ID not found)

After term returned (back on Create GDM page)
- Prepend ID before term name, return term name here (as on modal)

Free text choice:
- Add box for term name (<= 200 characters)
- Make Description box OR phenotypes required (one or other)

@wrightmw let me know if I've forgotten anything

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up a new instance of the add-disease modal for you to review:
https://1328-jz-disease-id-types-7b8fb1d-jzhen.demo.clinicalgenome.org

The changes are so far only implemented for the GDM, and you can now save the GDM.

**Comment by selinad** [comment]
First -- wow!  Lots of progress and many things working great!  Here are maybe more comments than you need for this instance (meaning I know you have been working on data model changes and you may not have had a chance to get there yet) and a few bugs.  

Super work, @jimmyzhen !  thank you.

Comments:

- add link to searching MonDO on create Gene-Disease page (under "Please add disease")
-  could probably remove "please" from above title as it's mandatory; maybe "Select disease"
- in example for entering ID, 
- add text re where to find ID in OLS (Enter the term "id" found in the Term Info box for the term as displayed in the OLS).  Change "Enter ID from MonDO search" to "Enter the term "id" and then add "term "id" can be found in the "Term info" box displayed on the right hand side on the term page of the OLS"
 Change "Select this checkbox if you are unable to find a known disease ID" to "Note: We strongly encourage use of a MonDO ontology term and therefore specific database identifier for a disease. If you have searched and there is no appropriate database identifier you may contact us at clingen-helpdesk@lists.stanford.edu and/or create a term using free text.  Check here to find free text option" ( @wrightmw feel free to edit)
- once a disease is returned via API, can free text option disappear?  Slightly confusing + we want to discourage use when possible
- like having curator's name returned for free text!  Could we say something like 'Non-ID term" when it is returned (where it says Please add disease?)
- Where would they find a free text description and the HPO terms?  I'm thinking we should display those on return?
- is there a limit on term description?  Right now, it's too long:
![screen shot 2017-05-22 at 10 33 32 am](https://cloud.githubusercontent.com/assets/11320314/26321040/22479ea0-3eda-11e7-84de-3af06090ef5e.png)


Bug
- bug if I hit submit after entering free text fields (all) and then forget to add moi -- won't submit and there is no error report
![screen shot 2017-05-22 at 10 32 12 am](https://cloud.githubusercontent.com/assets/11320314/26321009/fee9f552-3ed9-11e7-884f-ee3a58c15dd3.png)
- if I edit disease once in record central, save does not update the record central text, even if I refresh (maybe you're not there yet!) ;-)
- once I add piece of evidence, edit button for disease still there...

**Comment by selinad** [comment]
@jimmyzhen -- it may be that you have it that another curator can't edit the disease if the first has entered evidence -- I'm finding that!  Apologies, that might not be a bug.  Testing a bit more to check behavior.

**Comment by selinad** [comment]
@jimmyzhen -- great!  A second curator cannot edit the disease.  However, it does seem the first curator who created the disease term name with free text can edit it AFTER a second curator has added a piece of evidence -- it may be in your plans already, but want to disallow this ( @wrightmw do you agree?)

**Comment by selinad** [comment]
@jimmyzhen just noticed the FREETEXT id -- great!  Not sure if we need to display this...what do you think @wrightmw ?

**Comment by selinad** [comment]
@jimmyzhen sorry -- one more thing.  Is there a way to block entry of an OMIA ID?  If not no worries this round.  These are for non-human animals. e.g. OMIA:001260

Hopefully, no one would enter this, but if we can block it, it's always better -- let me know; I can make a ticket for July.

@wrightmw we are going to need to create help documentation for using MonDO...

**Comment by wrightmw** [comment]
I think the FreeText ID should be internal... we shouldn't display it.
@selinad I would think MonDO help documentation is desirable rather than essential for this release. The current help docs need to be updated based on the changes to the interfaces, and it would be desirable to add some MonDO help documentation at the same time but I think this is desirable rather than essential (i.e. if we have not had time to add this MonDO help doc then I don't think our release should be delayed to wait for this) .

**Comment by selinad** [comment]
thx @wrightmw I agree re the FREETEXT ID

It's rare, but I disagree re help -- we need to explain they can only pick terms with MONDO in blue box on the OLS (they will want to know why they can't use ORPHA15, for example), etc.  I don't think it has to be complicated, but they will need some guidance.  I believe JG mentioned this on a call already, too.  They are likely to have had little/no exposure to MonDO.

**Comment by selinad** [comment]
One more quick thing @jimmyzhen -- we were going to require HPO terms or Description for free text entries (just to put in writing).

**Comment by jimmyzhen** [comment]
@selinad, I can disallow the entry of OMIA IDs in the add disease modal.

**Comment by selinad** [comment]
@jimmyzhen thx re OMIA -- let me know if that is time intensive and we can evaluate against other features.

Here is what @wrightmw and I drew up for editing diseases ( @jimmyzhen I'm trying out the task list, although it may not be appropriate for this list!):

- [ ] As we spoke about, a GDM is editable (by creator only) until someone adds a PMID (doesn't matter who) -- if we have time, we will make it so the creator can edit until a 2nd participant has added evidence to the GDM.  This means the Disease Edit button will be available next to the Gene:Disease name for the creator until a PMID is added to the record by anyone

- [ ] For full text -- the curators will need to be able to view the Description (paragraph length) and HPO terms, as well as the term.  They should be able to get to this after entering the free text in GDM, next to the disease term int he GDM record's header, and wherever it is displayed in the interface (first 2 most important). A couple of ideas for implementation:

- hover over that gives description / HPO terms 
- display part of text in header under disease with the dotted underline so scroll over shows all of the text (for Description)
- View button that pops up non-editable modal (see next task item though)

- [ ] Editing free text term name: The _term name_  (phrase) is not editable except as is allowed for a MonDO term (i.e. behaves just like an ID).  If they want to change it to an ontology term, we will help them with this rather than allowing this to be changed to a term (at least for this version)

- [ ] For the **free text _Description_, and HPO terms** here are a list of options -- you can decide based on implementation time (from least preferred to most preferred)

- allow them to be edited in same circumstances as MonDO term and free text term name
- allow creator to ADD information at any time (not edit -- that can only happen before PMID added to GDM)
- allow any participant to ADD information to it at any time 

- [ ] For diseases within a Group, Family, Individual

- can we allow them to copy free text term from GDM to the G, F, or I -- @wrightmw and I think this would help a lot
- put edit button by each disease term (MonDO or free text) -- they can only delete a free text term, they could delete or change a MonDO term; we would also need a +Disease button (to add an additional disease)

We think all of the above will work, but happy to walk through it with you!   -S

**Comment by jimmyzhen** [comment]
The flow of add/delete diseases within a Group, Family, Individual and Interpretation:

![img_5611](https://cloud.githubusercontent.com/assets/6956310/26428011/493c572e-4094-11e7-9dcd-0c24b44b966f.JPG)

**Comment by selinad** [comment]
Notes from our discussion today:
( @wrightmw please feel free to make any edit)

### Create GDM page:
- [ ] Change text to "Search MonDO using OLS"

### Modal before save:
- [ ] for checkbox: "Check this box _only_ if you were unable to find a suitable ontology term and need to enter a free text term"
- [ ] add space between "searched" and "and" (says "searchedand" right now)
- [ ] put "OR" in stead of comma in example for desired ID -- let's put them in order of Orphanet ID, DOID, OMIM ID (need to add ORPHAID -- can use existing example
- [ ] Quick to put the Note in a yellow box?  Would stand out better and be more like a warning

### Modal after save:
- [ ] Include this directly before the returned definition for a MonDO term: "**Definition:**"; if there is not definition, I believe this space is empty, in which case, would not show "Definition:" or would put "none" after it (do what is simplest)

### Free text:
- [ ] Change "Rich text disease name" to "Disease name" and put in entry box: "short phrase (max 100 characters)"
- [ ] Change "Disease description" to "Disease definition" and put in entry box: "Describe this disease"
- [ ] Between the 1st and 2nd boxes, add text: Either a definition or HPO term(s) is required to describe this disease (both fields may be used)"
- [ ] Add warning note at top (in yellow box if possible): "Use of free text could result in different terms being used for the same disease.  Please make certain there is no appropriate ontology term before applying a free text disease name"

Resulting Create GDM (following save):
- [ ] yellow text box needs text change from "Currently, the above options (gene, disease, mode of inheritance, or adjective) cannot be altered for a Gene:Disease record once the record has been created. This includes adding an adjective to a Gene:Disease:Mode of inheritance record that has already been created or editing an adjective associated with a record." to "The above options (gene, disease, mode of inheritance, or adjective) can be altered for a Gene:Disease record up until a PMID has been added to the record. This includes adding an adjective to a Gene:Disease:Mode of inheritance record that has already been created or editing an adjective associated with a record." 
- [ ] For a MonDO disease as well as free text, please allow a disease to be updated until a PMID added
- [ ] fix display of disease name if text too long (test up to 100 characters)

**Comment by selinad** [comment]
One more potential change, @jimmyzhen as I see you may already have a check next to the item -- seeking @wrightmw 's opinion first:

For the checkbox -- how about: "Check this box to indicate you were unable to find a suitable ontology term and need to create a free text term"

**Comment by selinad** [comment]
@jimmyzhen As we just discussed, Case-Control also has a Disease field (in addition to G, F, I and the Create GDM).

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Below are the UIs I have implemented for Group so far:
![image](https://cloud.githubusercontent.com/assets/6956310/26506753/72f7db14-4202-11e7-8448-802377a0f855.png)
![image](https://cloud.githubusercontent.com/assets/6956310/26506768/81db11fa-4202-11e7-8d32-63cf484f83a8.png)

**Two questions:**
1. Shall we modify the text messages in the yellow warning box?
2. How would you want the button arrangement to look like for Family and Individual if we also need to include ability to copy disease from the group (e.g. "Copy Orphanet IDs from Associated Group")?

**Comment by selinad** [comment]
Looks great @jimmyzhen !  

1. Yes, we should definitely alter the yellow box.  How about "Please enter a disease term and/or phenotype(s); phenotypes may be entered using HPO ID(s) (preferred) or free text when there is no appropriate HPO ID."

2. Did we talk about having 2 buttons for F and I?  e.g. Copy disease from Gene-Disease Record" and "Copy disease from Group"?  We were thinking we didn't need to add logic now if the GDM disease = Group disease.

**Comment by selinad** [comment]
@jimmyzhen per our pow-wow with @wrightmw too, let's revise answer to number 2 above so that we don't have Copy disease from Gene-Disease record on F and I pages.  Instead, just on the G page and then the F and I pages have "Copy disease from Group" (or whatever current language is), "Copy disease from Family."

One item: For Case-Control, could we have "Copy disease from Gene-Disease record" there?  Not urgent if it doesn't work this release, but maybe it's easier as it will be consistent with Group.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have a new instance spun for what I have so far:
https://1328-jz-disease-id-types-fbd3dba-jzhen.demo.clinicalgenome.org

The add-disease modal has been implemented throughout the GCI, but not yet in VCI.

A known issue - if the entered disease is not already in the test database, it is not somehow captured in the curation objects (e.g. group, family, individual) 😭

**Comment by selinad** [comment]
@jimmyzhen you are incredible!

### Create GDM page

- [ ] remove the link for "OLS" text (I'm sorry as you implemented it as specified -- I'm now worried they will choose a non-MonDO term, so I think it's best to remove the link to OLS

Note: the following work great!
* Can edit disease up until PMID added by myself or 2nd curator 👍 
* OMIA can't be added -- perfect error message 👍 
* cannot create identical record (G-D-Moi is unique) 👍 
* Can curate on paper added by another curator (different ticket, but works well -- message not removed yet, but Chris' probably not yet merged 👍 
* Description link works great (clicking on it gives description) 👍 

Next times:
* If there is no description, there is no feedback about this -- we can fix this in future release

### Modal

- [ ]  remove remove the link for "OLS" text (as on Create GDM page)

### Group
Wow!  Works really well -- I tried every permutation I could think of wrt to adding / editing disease and everything held. 👍 

### Family 
Also works great!  Can copy disease to individual
- [ ] There are "*" for disease and phenotype, but these not required for Family so need to be removed (seems to behave correctly)
- [ ] would it be ok to change text from "Disease(s) in Common:" to Disease(s) in Common for Family:" ?  
- [ ] Some logic has been removed (checking against current demo) -- if I Copy disease from Family to individual, but don't enter label for proband, it lets me save but doesn't store disease.....I can also add label and no disease and it lets me store, but this isn't OK as disease is required for the proband....see behavior in current demo version.  The proband then can't be edited without including a disease, which is good, but should not be able to save proband in Family without disease and label.

Small items:

- [ ] Could the Group disease that could be copied be returned in bold above the Copy button?  For some reason, they it doesn't jump out at user and they are in bold when returned on modal and in header, so user used to it 
Individual

- [ ] The error button when disease is not included appears up by disease rather than by Save button -- can it move down by Save button like other error messages?  Right now, there is no feedback by Save button as to why form is not saving, so it seems like it is frozen.  Also, the placement of error message is a little funny with the buttons (not a big deal for this release)
![screen shot 2017-05-28 at 12 09 17 pm](https://cloud.githubusercontent.com/assets/11320314/26531475/994f8742-439e-11e7-9884-6176b6c05a1c.png)


### Individual

- [ ] Related to above issue with disease not being required for proband created with Family.  When I tried to save that individual without a disease, got error, as I should.  But then when I copied the disease from Family using the button, freezes on Save:
![screen shot 2017-05-28 at 12 45 54 pm](https://cloud.githubusercontent.com/assets/11320314/26531705/b8be8448-43a3-11e7-8644-cb56d6cfd486.png)

- [ ]  @wrightmw do you think we should remove ability to "Copy disease from Gene-Disease Record" for a new individual that is not a proband? 

I'll keep testing -- there is a lot going on.  Absolutely fantastic, hard work, @jimmyzhen -- thank you!

**Comment by jimmyzhen** [comment]
> A known issue - if the entered disease is not already in the test database, it is not somehow captured in the curation objects (e.g. group, family, individual) 😭

I've fixed the bug mentioned above and patched the current instance with the fix.

**Comment by selinad** [comment]
@jimmyzhen -- does this explain the bug or are you saying this is a new issue?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up a new instance for you to review:
https://1328-jz-disease-id-types-e668045-jzhen.demo.clinicalgenome.org

This instance includes the new add-disease modal for interpretation in VCI, along those in the GCI. Let me know if you have any questions.

**Comment by selinad** [comment]
Hi @jimmyzhen Thank you!  Nice!

### Comments on VCI:

- [ ] Works great!
- [ ] The yellow box is directly on top of the check box free text
- [ ] I'm wondering if the Delete button should be red? @wrightmw ?  I think it would be similar to other delete buttons in the interface
- [ ] Links in header for disease work great, and header title looks great!
- [ ] Change error message to "Either a description or HPO term(s) (e.g. HP:0000001) is required"
<img width="581" alt="screen shot 2017-05-30 at 9 19 47 pm" src="https://cloud.githubusercontent.com/assets/11320314/26615699/d4015c2c-457d-11e7-9f9f-2538aa994bfc.png">

- [ ]  Free text works great!  Displays correctly in header and title, is editable

**Comment by selinad** [comment]
Hi @jimmyzhen -- I tried entering a free text again and found this (free text was the first thing I entered this time).  What's strange is no disease term is showing even though the Delete button is active
<img width="1435" alt="screen shot 2017-05-30 at 9 47 10 pm" src="https://cloud.githubusercontent.com/assets/11320314/26616189/9a7b7ec0-4581-11e7-99ec-c1d801b4ce6d.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

The strange behavior (e.g. "The yellow box is directly on top of the check box free text") and console error you were seeing might have something to do with a bug in the "Delete disease" button in the VCI. I've addressed the bug and patched the instance. Please try again after refreshing the browser page.

Also, I've added a "View description" link in the VCI header if a disease term has description.

Lastly, I tried the red delete disease button in the VCI. It seemed a bit too much visually, and so I am using the same blue color for the button (as we do for the mode of inheritance association button).

**Comment by selinad** [comment]
@jimmyzhen a little confused as I still see the yellow box sitting on top of the text box, but the disease seems to be functioning correctly:
<img width="600" alt="screen shot 2017-05-31 at 10 42 23 am" src="https://cloud.githubusercontent.com/assets/11320314/26646124/566e69fe-45ef-11e7-8af8-8dfb673d2e7d.png">

**Comment by selinad** [comment]
@jimmyzhen -- the View Description is great, and the link to the OLS for the VCI.  The Description box pops up quite a bit below the link, but I think it's great for now -- thanks!

Re Disease button -- I like the icon, but I'm worried about the blue -- would it be easy to see the red? (do you have a screen capture).  Also, it would be more consistent with the rest of the UI to use red, I think....

**Comment by selinad** [comment]
One thought for the MOI button -- could it be the same blue as the update button for evaluations?  Delete and Edit are different and we use the lighter blue for "Update" (= Edit)

**Comment by wrightmw** [comment]
@jimmyzhen @selinad I like the dustbin on the Delete button but I think it should be red to make it more obvious to a curator that they are about to delete the disease.

**Comment by selinad** [comment]
Hi @jimmyzhen 

Not a big deal -- it would be great if this either worked like the "View Definition" link you have elsewhere or if easier, was an external link rather than something they'd have to copy/paste.

<img width="404" alt="screen shot 2017-05-31 at 10 51 15 am" src="https://cloud.githubusercontent.com/assets/11320314/26650527/8f680a1c-45fe-11e7-86e2-7e089523fa14.png">

**Comment by selinad** [comment]
![screen shot 2017-05-31 at 12 54 26 pm](https://cloud.githubusercontent.com/assets/11320314/26651039/55ab4d82-4600-11e7-8cc0-110db4798ef3.png)

HI @jimmyzhen -- a couple of small things:
- [ ] maybe you have not had time to implement, but remove the link from the text "OLS" (I think it's too confusing for users) on the very top line
- [ ] I'm thinking we may need to be clearer with this text: "Enter the term "id" (Term "id" can be found in the "Term info" box displayed on the right hand side on the term page of the OLS): *"  _Change to_: "Enter a MonDO term "id" from MonDO OLS search (Orphanet, DOID, OMIM and NCIt id's allowed).  The term "id" can be found in the "Term info" box displayed on the right hand side of the OLS term page -- e.g. Orphanet:93545): *"  The Orphanet:93545 can be an external link to https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOrphanet_93545) @wrightmw does this sound good?
- [ ] If we are able to restrict to Orphanet, DOID, NCIt, and OMIM, could you add an NCIt example? e.g. NCIT:C4089, https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C4089)
- [ ] In yellow box, could we add "an allowed" where I've indicated it in caps: "Note: We strongly encourage use of AN ALLOWED MonDO ontology term and therefore specific database identifier for a disease. If you have searched and there is no appropriate database identifier you may contact us at clingen-helpdesk@lists.stanford.edu and/or create a term using free text."

**Comment by selinad** [comment]
@jimmyzhen is there a way to make the Description text a little wider on return at very minimal time cost -- this is an extreme example.  Not worth any amount of time if not.  Another possibility would be the "View Description" link that you use elsewhere (if possible from the modal)

The 100 characters works great!

![screen shot 2017-05-31 at 1 34 54 pm](https://cloud.githubusercontent.com/assets/11320314/26652832/070e4d36-4606-11e7-8f54-9425f0360961.png)

Also, would it be quick to insert a space between HPO terms on the following display?
![screen shot 2017-05-31 at 1 37 17 pm](https://cloud.githubusercontent.com/assets/11320314/26652948/747edeb2-4606-11e7-9822-befc39240262.png)

**Comment by selinad** [comment]
@jimmyzhen There are other places where OLS is a link (sorry!).  Here's an example that will occur on G, F, I and I assume Case-Control:
![screen shot 2017-05-31 at 1 49 08 pm](https://cloud.githubusercontent.com/assets/11320314/26653474/19a70698-4608-11e7-9e2f-45f3eeee2c13.png)



Is there an easy way for you to find them (I'll keep adding as I see).

**Comment by wrightmw** [comment]
In the GDM, once a curator Saves free text, e.g. below:
![screen shot 2017-05-31 at 2 23 24 pm](https://cloud.githubusercontent.com/assets/15131169/26654791/f70cdafe-460c-11e7-8922-06ae8d98dce2.png)
 Then they do not have an option to change the free text to an ID, they are stuck on free text...e.g. see below:
![screen shot 2017-05-31 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/15131169/26654827/0de9c4f8-460d-11e7-9364-3eb101df602b.png)
Curators can delete the free text if they refresh the page, but there is no information to tell them this. 
This is different from the functionality for IDs, which can be changed within the GDM. Which is confusing.
@selinad

**Comment by selinad** [comment]
HI @wrightmw - yes, @jimmyzhen and I talked about this and felt we should hold given all the other things that needed to happen at the time, with the plan to revisit closer to the release when everything else had been implemented.  I agree it's potentially confusing -- it's a bigger problem once the record is created and before a PMID added.....but we have provided a lot more functionality that previously existed...

**Comment by selinad** [comment]
@jimmyzhen I don't think the URL was here before?  It's good as it goes to OMIM.  Is it coming directly from the API?  Could it be the hyperlink to text like "View term at source's site"?  (I'm sure there's something better, but I'm thinking it will be hard to pick out OMIM or Disease Ontology, etc...

![screen shot 2017-05-31 at 4 24 04 pm](https://cloud.githubusercontent.com/assets/11320314/26658255/a73ae7c6-461d-11e7-98ed-b7b59764159f.png)

**Comment by selinad** [comment]
@jimmyzhen -- for the View page when a free text term, Definition and HPO terms added (copied from GDM), it only shows the free text term.  It's a bit confusing as there are fields for HPO for phenotype.  Could you show the Definition and disease associated HPO terms on the View, maybe below the term name but indented?  the fields would be empty if none entered.

e.g. 

Short term
      Description
      HPO terms

**Comment by selinad** [comment]
Hi @jimmyzhen Would it be a quick request to have it so that every time there is a description, use the "View Description" link that you have implemented in header -- I think it could get really long displaying on G, F, I pages like here (even tho this one short)
![screen shot 2017-05-31 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/11320314/26658792/4677ec46-4621-11e7-94a3-1f8d03965218.png)
 (ok for next release too)

**Comment by selinad** [comment]
- [ ] Hi @jimmyzhen per our discussion today let's check that the ID begins with one of the following: OMIM, Orphanet, DOID or NCIT (don't know whether you include colons).  Another option is to "black list" the DC: terms (less preferred).  Please let me know if this becomes unreasonable in terms of time.

Thx! - Selina

**Comment by wrightmw** [comment]
This is a slightly odd minor bug. I filled out the GDM but the gene symbol was incorrect... I corrected the gene symbol but it would then not me save the GDM, even though it now had the correct approved symbol:
![screen shot 2017-05-31 at 5 50 57 pm](https://cloud.githubusercontent.com/assets/15131169/26660006/f21928be-4629-11e7-9e44-4f66dd33e842.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is how the disease and MOI buttons look in VCI:
![image](https://cloud.githubusercontent.com/assets/6956310/26704709/f11a66d2-46e5-11e7-8cfb-fa25822a121e.png)

**Comment by selinad** [comment]
I like it @jimmyzhen !

**Comment by wrightmw** [comment]
I like it also!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is how the delete button looks in GCI:
![image](https://cloud.githubusercontent.com/assets/6956310/26705276/1134c0c6-46ea-11e7-967e-a66348dc81dc.png)

**Comment by wrightmw** [comment]
I think the red border needs to be a bit thicker.

**Comment by selinad** [comment]
Me too -- you were going to try the text and icon red, too, so maybe that will help?  I could go with straight red, tho, if you want to save time!

**Comment by jimmyzhen** [comment]
I knew you would ask for it ;)

So here it is:
![image](https://cloud.githubusercontent.com/assets/6956310/26705555/ba15d134-46eb-11e7-904e-9090a2caae59.png)

**Comment by selinad** [comment]
Hi @jimmyzhen the new Reset implementation is fantastic -- thank you so much for your hard work implementing this.

As we discussed, I did uncover one bug:  
If I create a GDM with OMIM:125851 and then edit it from within the record by hitting reset and then adding a free text disease, save that, and then hit edit again, the following appears (OMIM definition saved for Definition part (note: the HPO terms appeared in the header, but not the View Definition, so it is not being displayed on the UI):
![screen shot 2017-06-06 at 10 01 01 am](https://user-images.githubusercontent.com/11320314/26842080-7600063c-4aa0-11e7-935f-bd19964dc672.png)

**Comment by selinad** [comment]
One more thing -- if I hit reset on the above and re-enter the OMIM and Save, it brings back but does not save the OMIM term.  After doing the above, this appears:

![screen shot 2017-06-06 at 10 14 15 am](https://user-images.githubusercontent.com/11320314/26842244-f71539c2-4aa0-11e7-8597-c97da8dd72d0.png)

**Comment by selinad** [comment]
Here is a similar bug:

1. Create GDM with free text disease and free text descripton
2. Edit disease from GDM -- hit reset and then enter DOID:9409; Save.  All looks good in GDM
3. Edit disease from GDM -- hit reset and then enter new free text term and HPO terms -- Bug in that it does not save new free tex -- still has DOID:9409t:

![screen shot 2017-06-06 at 10 28 34 am](https://user-images.githubusercontent.com/11320314/26842812-eb143342-4aa2-11e7-87b4-e4f93341d625.png)

**Comment by selinad** [comment]
Pasting screen capture below as I had a Chrome crash as I was writing this that may have been related: ![screen shot 2017-06-06 at 10 48 20 am](https://user-images.githubusercontent.com/11320314/26843726-1301b444-4aa6-11e7-97ed-7cc521320eed.png)
Disease is not required for Family, so did not expect to see error, but did see a spinning wheel on Save and then Chrome crash happened
![screen shot 2017-06-06 at 10 44 55 am](https://user-images.githubusercontent.com/11320314/26843750-28611bae-4aa6-11e7-80fb-9e763d1dc0d7.png)

**Comment by selinad** [comment]
@jimmyzhen I repeated the above -- if I Copy the disease from the Group, then Delete it, then save without providing the # of affecteds, spinning wheel happens.

**Comment by selinad** [comment]
@jimmyzhen I accidentally typed in the wrong DOID (9049 instead of 9409) and got this -- we should not allow them to add an obsolete ID (I was able to add it).  Is there a quick way to rectify this?  If not, I will make a ticket for R12 (it's on the curator to verify it's correct -- seeing this raised my attention so I checked OLS and discovered my mistake, but we should prevent if we can)

![screen shot 2017-06-06 at 11 10 09 am](https://user-images.githubusercontent.com/11320314/26844605-d39ef3cc-4aa8-11e7-8648-9e8ddc9ca1bd.png)

**Comment by selinad** [comment]
@jimmyzhen update to issue where I thought a disease needed to be added and deleted to get error  -- it does not.  
1. add Family from Group that has associated disease
2. label Family
3. hit save
4. get error that need to add #affecteds.
5. fix error and hit Save
6. get spinning wheel

Here's error message:
![screen shot 2017-06-06 at 11 25 27 am](https://user-images.githubusercontent.com/11320314/26845334-0649bb2a-4aab-11e7-9ce1-059810d87ca7.png)

**Comment by selinad** [comment]
@jimmyzhen lots of stuff looks great form Family and Individual according to your test steps.  One thing that might be fixed when you fix so F disease not required -- if there is no disease associated with Family, still have 'Copy disease from Family' button when creating the Individual on that Family page -- doesn't work, but I think it shouldn't be there until a disease added?

![screen shot 2017-06-06 at 12 01 19 pm](https://user-images.githubusercontent.com/11320314/26846922-19300d3e-4ab0-11e7-8806-eea48cdb0afc.png)

The button doesn't appear in the current curation-test until a disease is added:
![screen shot 2017-06-06 at 12 03 43 pm](https://user-images.githubusercontent.com/11320314/26846968-3f911eaa-4ab0-11e7-8454-a85e6ad9c54f.png)

**Comment by selinad** [comment]
For Case-Control -- is it quick to add and "OR" button as for other (can easily move to R12)

<img width="980" alt="screen shot 2017-06-01 at 1 07 49 pm" src="https://user-images.githubusercontent.com/11320314/26847150-db0c8112-4ab0-11e7-878e-d6ba6572d308.png">

**Comment by jimmyzhen** [comment]
@selinad, I added a label for the obsolete term:
![image](https://user-images.githubusercontent.com/6956310/26847294-6147acf2-4ab1-11e7-8f02-2905bffeef4f.png)

**Comment by selinad** [comment]
@jimmyzhen that is FANTASTIC.  Thank you!

**Comment by selinad** [comment]
@jimmyzhen everything else I tested on the GCI looked great!

Re VCI -- looks great except for one issue.

If I choose a disease and a moi AND adjective, then update the moi, changing the moi -- adjective menu changes to select, but hitting save keeps old adjective -- e.g.

![screen shot 2017-06-06 at 12 19 07 pm](https://user-images.githubusercontent.com/11320314/26847578-6c6e0a94-4ab2-11e7-8c25-a91c4d22bde6.png)

**Comment by selinad** [comment]
Had this on wrong ticket -- moving over:

@jimmyzhen just starting to test the updated instance.

Here's something someone wouldn't try, but might -- if I go to Edit a disease from GDM and decide I don't want to make a change, so hit Save, it stalls -- I don't think this is a big deal as if I were smart I would have hit Cancel ;-).  But, if it's a quick fix (otherwise, we can move to R12 if we decide we want to deal with it)
<img width="621" alt="screen shot 2017-06-06 at 7 45 11 pm" src="https://user-images.githubusercontent.com/11320314/26860099-ea7dae38-4af0-11e7-9ce3-6998e0ec2baf.png">
![screen shot 2017-06-06 at 7 47 26 pm](https://user-images.githubusercontent.com/11320314/26860114-06fa7d5c-4af1-11e7-8afe-25373293cc84.png)

**Comment by selinad** [comment]
Had this on wrong ticket -- moving over:

@jimmyzhen I edited from a NCIt to a free text, adding term and HPO -- worked great.  I then hit Edit and tried to add a Description (not changing anything else) -- this was not stored (the Description for the free text)

I should say that if I reset from there and add a new free text term, HPO and definition, that all saves properly

Here's an observation -- if I add an HPO term and no def, saves correct; if I add a def and no HPO term, does not save free text disease (leaves mondo ID disease)

And if I then Reset and add Orphanet, all looks good!

**Comment by selinad** [comment]
@jimmyzhen the RESET button works great now!!  Excellent work.

Also, the VCI moi works perfectly now!

The Obsolete tag is perfect -- in a future release maybe we can suppress Save button (hopefully no one will save an obsolete term....)

The Copy disease button from Group appears only when disease added -- great!

One bug -- it seems like disease is not saving for a family added from a group:
Added free text:
<img width="432" alt="screen shot 2017-06-07 at 7 24 11 pm" src="https://user-images.githubusercontent.com/11320314/26909698-45af961a-4bb7-11e7-8e87-4b4045bbbef4.png">

after saving and selecting edit, got this : (
<img width="497" alt="screen shot 2017-06-07 at 7 24 30 pm" src="https://user-images.githubusercontent.com/11320314/26909705-504db39a-4bb7-11e7-9d93-b866cae11340.png">


Same for a MonDO ID:
<img width="469" alt="screen shot 2017-06-07 at 7 25 31 pm" src="https://user-images.githubusercontent.com/11320314/26909710-5b6f83d4-4bb7-11e7-8af5-7f76b343fa38.png">

<img width="553" alt="screen shot 2017-06-07 at 7 25 51 pm" src="https://user-images.githubusercontent.com/11320314/26909712-6736801e-4bb7-11e7-89b0-eb0a39fb1dfa.png">

**Comment by selinad** [comment]
Using ID from GDM throughout
G: Copy disease from GDM
F: Copy disease from G
I: Copy disease from F
👍 

Using free text from GDM throughout
G: Copy disease from GDM
F: Copy disease from G
I: Copy disease from F
👍 

Using new disease ID for group 
G; Give new ID (different from GDM)
F: Copy this to F
I: Copy from F to I
👍 

Using new diseaseID for G, then for F, then for I
G; give new ID (different from GDM
F: give new ID (different from G)
I: give new ID (different from F)
👍 

Family not from group -- seems to work now; can save new disease and edit that new disease

@jimmyzhen I cannot reproduce what I saw earlier.  Question: would adding the same disease that one would copy from a GDM or G or F cause a problem?

**Comment by selinad** [comment]
@jimmyzhen I actually can repeat
G: Copy ID from GDM
F: Add free text term name and Description (do not copy from G)
Save -- edit Family and do not see disease

**Comment by selinad** [comment]
@jimmyzhen in your newest instance, these bugs are fixed!

Also, the disease displayed in View for proband w/o segregating evidence, so I could not repeat that problem you thought you saw.  I did see a problem with disease not displaying on view in an earlier instance, but also couldn't recreate (wonder if it was related to above bugs you fixed)

**Comment by selinad** [comment]
@jimmyzhen @gto389 --
GDMs are looking great -- only one that doesn't seem right so far:

production
https://curation.clinicalgenome.org/curation-central/?gdm=c6622002-6d82-4bc4-94d5-e81822d006f2&pmid=26752647

instance
https://r11-rc1-24b226b-jzhen.demo.clinicalgenome.org/curation-central/?gdm=c6622002-6d82-4bc4-94d5-e81822d006f2&pmid=26752647

no GDM showing….

**Comment by selinad** [comment]
@jimmyzhen 

I worked hard to break the disease modal, but couldn't -- everything worked great.  Including in the VCI.

@jimmyzhen @gto389 

For GCI --I have tested many GDMs and many groups, families, and individuals and cannot break it other than the one bug above.  Looks fantastic! I can go through in a more methodical fashion.

Re the VCI and the disease insertion, this one looks good (different term name for same disease, so it is correct), as do most others:
production
https://curation.clinicalgenome.org/variant-central/?variant=e1de02b1-a7e6-4ca7-9377-8b87fbc70569
instance 
https://r11-rc1-24b226b-jzhen.demo.clinicalgenome.org/variant-central/?variant=e1de02b1-a7e6-4ca7-9377-8b87fbc70569

However, I don't think this one is right -- these are 2 different diseases, but maybe it's related to bug in GDM reported above (same disease involved)

https://curation.clinicalgenome.org/variant-central/?variant=8664157b-1df6-41bc-ac5a-85c0e6db7713

https://r11-rc1-24b226b-jzhen.demo.clinicalgenome.org/variant-central/?variant=8664157b-1df6-41bc-ac5a-85c0e6db7713

What is the bug with that disease in the GDM?  Wondering if it makes sense for the problem in the VCI as well.

Amazing work!!!  Retiring as I have an early rise, but I think things are in very good shape overall. 👍

**Comment by jimmyzhen** [comment]
Hi @selinad, @gto389,

The bug with disease in the GDM and Interpretation in question was entirely my error when I created the orpha-uuid to disease-uuid mappings. This error affected the mappings of Orphanet_1020 and Orphanet_1037 diseases that are individually associated with an interpretation and a GDM.

I've corrected the error in this RC instance. The GDM and Interpretation records in question are now showing the expected data:

https://r11-rc1-24b226b-jzhen.demo.clinicalgenome.org/curation-central/?gdm=c6622002-6d82-4bc4-94d5-e81822d006f2&pmid=26752647

https://r11-rc1-24b226b-jzhen.demo.clinicalgenome.org/variant-central/?variant=8664157b-1df6-41bc-ac5a-85c0e6db7713

**Comment by selinad** [comment]
thx @jimmyzhen !  It looks like the instance is down now, so I can't double-check, but many thanks for fixing.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Due to additional changes and fixes in the upgrade scripts, I'd spun up another new instance of the RC: https://r11-rc1-ebe540c-jzhen.demo.clinicalgenome.org

You may verify them at:
https://r11-rc1-ebe540c-jzhen.demo.clinicalgenome.org/curation-central/?gdm=c6622002-6d82-4bc4-94d5-e81822d006f2&pmid=26752647
https://r11-rc1-ebe540c-jzhen.demo.clinicalgenome.org/variant-central/?variant=8664157b-1df6-41bc-ac5a-85c0e6db7713

You can now also access the GDMs and Interpretations from their respective listing pages.

**Comment by selinad** [comment]
Hi @jimmyzhen unfortunately I found a problem when checking the experimental data that's related to this change (this is for Bioch Funct A)
![screen shot 2017-06-14 at 11 11 08 am](https://user-images.githubusercontent.com/11320314/27147672-8030f3b6-50f2-11e7-8e33-0087774852b8.png)

**Comment by selinad** [comment]
@jimmyzhen this is amazing work. Thank you for all of your efforts.

There were only a couple of  small issues, for which I've created tickets ( #1375 , #1376 )  -- otherwise looking great and I've pounded hard.  

Will check mappings now, including bug fix.

**Comment by selinad** [comment]
@jimmyzhen I've checked all GDMs and Interpretations -- with the one exception noted in #1377, all are correct.  I'm moving to Groups, Families and Individuals

**Comment by selinad** [comment]
Moving this to release ready -- only a couple of small problems and those have new tickets.  Checked for G, F, I with disease not found in GDM -- found 1 and it checked out correctly in the G, F, and I. 

Also found that the disease that had incorrect term name had propagated it to the I of that record, in keeping with how the file was used (unique mappings) -- meaning that mappings successfully went to GDM, G, F, and I.

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
