### ISSUE TITLE
Curator Affiliation - Selecting affiliation upon login

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1507]
Upon being authenticated by the **Auth0** login and prior to being taken to the **Dashboard** page, the user will be presented with a modal-like interface to select his/her affiliation for the curation session if the user has 2 or more affiliations. If the user has only 1 affiliation or is signing in as an individual, he/she will be directly taken to the **Dashboard** page without the need to go through the affiliation selection interface.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have started working on the affiliation and have spun up an instance to demo what I have done so far:
https://1507-jz-affiliation-v1.demo.clinicalgenome.org

**Scope of the test/review:**
1. Affiliation test data only consist of 5 entries.
2. Development work has only affected login and Dashboard page at this point.
3. Evidence test data configured to be associated with affiliations only consist of families at this point.

**Steps to test/review:**
1. Login with an Auth0 account and expect to see the affiliation modal being displayed (if your account is associated with one or more affiliations). Please reference the test data provided below.
2. In the affiliation modal, expect to see 4 options (including "Individual") from the selection dropdown menu.
3. If you don't select an option, expect to see the **Continue** button being disabled.
4. If you select any given option, expect to see the **Continue** button being enabled.
5. If you select the **Bustamante ClinGen Test Group 1** option and click **Continue**, expect to see the modal being closed and 3 **Family** evidence records being displayed on the **Dashboard** page.
6. If you select the **Bustamante ClinGen Test Group 2** option and click **Continue**, expect to see the modal being closed and only 1 **Family** evidence record being displayed on the **Dashboard** page.
7. If you select the **Selina Dwight Laboratory** or the **Mathew Wright Laboratory** option and click **Continue**, expect to see the modal being closed and no **Family** evidence records being displayed on the **Dashboard** page.
8. Click on the affiliated evidence links and expect to be taken to the expected **Family** evidence.

**Test affiliation data:**
```
{
	"affiliation_id": "10001",
	"affiliation_abbreviation": "Bustamante Group 1",
	"affiliation_fullname": "Bustamante ClinGen Test Group 1"
},
{
	"affiliation_id": "10002",
	"affiliation_abbreviation": "Bustamante Group 2",
	"affiliation_fullname": "Bustamante ClinGen Test Group 2"
},
{
	"affiliation_id": "10003",
	"affiliation_abbreviation": "Selina Lab",
	"affiliation_fullname": "Selina Dwight Laboratory"
},
{
	"affiliation_id": "10004",
	"affiliation_abbreviation": "Matt Lab",
	"affiliation_fullname": "Mathew Wright Laboratory"
},
{
	"affiliation_id": "10005",
	"affiliation_abbreviation": "RG Color Blind Group",
	"affiliation_fullname": "Red-Creen Color Blindness Working Group"
}
```

**Test user accounts with/without associated affiliations:**
```
Will be provided offline.
```

**Comment by wrightmw** [comment]
@jimmyzhen 
Assessing this purely in terms of being presented with the correct Affiliation options based upon login persona, this looks fantastic. For each of my personas I can only access the correct options.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up a new instance for you to review the progress of the affiliation implementation:
https://1507-jz-affiliaton-v2.demo.clinicalgenome.org

**Scope of the test/review in this newer version:**
1. Affiliation test data only consist of 5 entries (aka 5 affiliations/groups).
2. Development work has been extended to evidence curation and interpretations (means now you can save an evidence with an affiliation), in addition to the login and Dashboard page.
3. Evidence test data configured to be associated with affiliations now consist of group, family, individual, case-control, experimental and interpretation.
4. The Dashboard page has been reorganized in the attempt to deal with the addition of various affiliated evidence entries and interpretations.

At this point, there are still many rough edges and things yet-to-be-done, such as:
1. The "Change Affiliation" button in the affiliation utility bar below the header is not yet functional.
2. Classification and evidence summary are not yet completed with the implementation of affiliation.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up another new instance:
https://1507-jz-affiliation.demo.clinicalgenome.org

Except for the Classification Matrix, I have implemented the affiliation in all the obvious places (that I can think of), including the Evidence Summary.

So please test it and provide any feedback that you may have. Thanks.

**Comment by selinad** [comment]
@jimmyzhen I'm so excited to test all of your hard work! 

First small item:
For this, can we simply say " Please select whether you would like to curate as part of an Affiliation"
![image](https://user-images.githubusercontent.com/11320314/34020846-5a692520-e0eb-11e7-9d48-fe5e128459cd.png)

And then say:
- Do not curate as part of an Affiliation
- Curate as part of Bustamante Group 1
- Curate as part of Bustamante Group 2
- etc.

Also, I think we should capitilize "Affiliation" throughout
@wrightmw let me know if you agree or have other thoughts

**Comment by selinad** [comment]
@jimmyzhen can you please remind me of what shows under "My Affiliation's Gene-Disease Records"? (looking GREAT so far!)

**Comment by selinad** [comment]
@jimmyzhen there was a little spillover when I added the new record (SMAD3)
![image](https://user-images.githubusercontent.com/11320314/34021129-fa52b8d4-e0ec-11e7-91fa-d2d82447f7ad.png)

**Comment by wrightmw** [comment]
@selinad 
Hmmm. I'm not overly keen on those proposed text changes. Isn't it better for the Affiliation they are selecting to ping out rather than being lost in the string of text? How about?:

No Affiliation (curating as yourself)
Bustamante Group 1
Bustamante Group 2
etc.

Although, if I'm being honest. I quite like it the way it is currently.

**Comment by selinad** [comment]
Just a quick thought -- do you want to use the briefcase icon instead of spelling out Dashboard here?
![image](https://user-images.githubusercontent.com/11320314/34021219-7571d586-e0ed-11e7-990a-27e962e1ed38.png)

Is that a light bulb?! :-) 👍

**Comment by selinad** [comment]
I'm not overly fond of adding extra text, but I thought it more explicit.  I could go either way on that one.

I don't care for as yourself (first of all, we are now using my) as one is curating as themselves even when they are part of a group, so I was looking to replace that in the instructions and in the pull-down. I think it sends a confusing message as actions will still be tracked to the curator.

**Comment by selinad** [comment]
@jimmyzhen what does "Summary/Provisional Classifications" mean?  I was thinking it would show status for that Affiliation?

**Comment by wrightmw** [comment]
Hmmm, but I also think it is good practice that what they select from this pulldown is the same text they will see  attributed to their edits in the interfaces (e.g. Selina Dwight, Bustamante Group 1, etc...)...so I think someone's name being shown is a nice touch.

**Comment by wrightmw** [comment]
How about?:
Selina Dwight (No Affiliation)
Bustamante Group 1
Bustamante Group 2
etc.

**Comment by selinad** [comment]
It's OK.... I'm not as hooked on it showing the name as it will display when the Dashboard pops up.  They will see their name when they enter evidence...

**Comment by jimmyzhen** [comment]
Hi @selinad,

> Just a quick thought -- do you want to use the briefcase icon instead of spelling out Dashboard here?
I am not sure whether the :briefcase: icon is clear enough to represent the Dashboard. What the :house: icon?

> Is that a light bulb?!
Yes, and I thought it is suitable to represent "Hint".

**Comment by selinad** [comment]
@jimmyzhen doh!  I meant the home button.  Sorry!

I like the lightbulb!

**Comment by wrightmw** [comment]
@selinad Yeah... happy to get rid of "yourself"
No Affiliation (Selina Dwight)
Bustamante Group 1
Bustamante Group 2
etc.

**Comment by selinad** [comment]
@jimmyzhen -- @wrightmw and I are unable to edit the same evidence in an Interpretation when we are curating as part of the same Affiliation -- he cannot edit mine below and I can't edit his...

![image](https://user-images.githubusercontent.com/11320314/34022653-4cf7d760-e0f5-11e7-8702-648a0a775b82.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

> what does "Summary/Provisional Classifications" mean? I was thinking it would show status for that Affiliation?

This is an implementation of status from the past. We can change that to the correct classification status.

**Comment by selinad** [comment]
@jimmyzhen When I go to Selina Dwight Laboratory, I see Interpretations @wrightmw created as part of a different Affiliation
![image](https://user-images.githubusercontent.com/11320314/34023027-90efedf2-e0f7-11e7-8f86-cb20699ba217.png)

The history is also showing incorrectly as I made those modifications as part of a different Affiliation (Bustamante Group 1)
![image](https://user-images.githubusercontent.com/11320314/34023061-b7164fa8-e0f7-11e7-9463-af5d350bef2b.png)

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
Some of the fields are squished when you add Experimental data:
![screen shot 2017-12-15 at 2 29 55 pm](https://user-images.githubusercontent.com/15131169/34063195-66fda88c-e1a5-11e7-8047-f0a393132573.png)

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
The headers within the GDM say "Participants", change to "Contributing Users"?:
![screen shot 2017-12-15 at 2 38 37 pm](https://user-images.githubusercontent.com/15131169/34063240-ae836ac0-e1a5-11e7-813f-3c2381723b0a.png)

**Comment by selinad** [comment]
@jimmyzhen here are the issues we've found:

- GCI: Curate variant seems to be by curator rather than Affiliation (i.e. I get same Curate Variant page when I edit it as a member of different Affiliations as it seems to belong to me rather than the Affiliation)
- VCI: Unable to save an evaluation of a criterion
- VCI: Interpretation should be per creator -- e..g if someone created an Interpretation as part of an Affiliation, it should read out that instead of curator's name:
![image](https://user-images.githubusercontent.com/11320314/34065127-d490a54e-e1b3-11e7-81c7-3a041caee05d.png)
This screen occurs even when I've switched Affiliations -- i.e. it's allowing me to edit an Interpretation I made as BG1 when I switch to SDLab1.....I think permissions are fine for editing evidence, however...

- Use "Contributors" to replace "Participants" in header and on View all list pages

**Comment by selinad** [comment]
@jimmyzhen -- the name of the existing Interpretation looks great and the associated edit button is gone now (yay!), but so is the Start Interpretation button so I can't start a new one when I am part of a new Affiliation (BG2):
![image](https://user-images.githubusercontent.com/11320314/34071852-09f1b38a-e232-11e7-9ae0-a62831fbf8c5.png)


It shows if it is a variant that hasn't been interpreted by another Affiliation:
![image](https://user-images.githubusercontent.com/11320314/34071896-cca58172-e232-11e7-99f9-4143f31da784.png)

I checked the edit button was there for an Affiliation where it already existed and that was perfect! (i.e. it shows when I am part of SD Laboratory and I can interpret it).

**Comment by jimmyzhen** [comment]
WOW :confused:

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I have spun up yet another new instance:
https://1507-jz-affiliation-fixes.demo.clinicalgenome.org

Please test it and verify the reported issues above being addressed in this instance. Thank you!

**Comment by wrightmw** [comment]
@jimmyzhen I'm still unable to Save an evaluation of a criterion.

**Comment by jimmyzhen** [comment]
I am terribly sorry 😓 I blew it ☹️

**Comment by wrightmw** [comment]
Oh @jimmyzhen , you have blown nothing! You are one of the hardest working person and dedicated people I know. This is just a temporary setback!

**Comment by jimmyzhen** [comment]
@wrightmw, I reverted some changes I made previously and you should be able to save interpretation evaluation again.

I briefly described the problem in this commit:
https://github.com/ClinGen/clincoded/commit/bd234572723c0d8c5bdc22282ca798435cda79b7

**Comment by wrightmw** [comment]
@jimmyzhen It's Saving Interpretations now, thanks.

**Comment by wrightmw** [comment]
I’m on the Caltrain and so these screenshots are from my iPad. I noticed just now that a Group I added as “Bustamante Group 1” is still editable when I’m “Matt Lab”. 
![0d46826f-80cd-4bca-9e02-6a90e2967045](https://user-images.githubusercontent.com/15131169/34082956-c43c4fa8-e31c-11e7-83b3-a0b5bc9bbd36.png)
![c82a5de7-db67-4a8c-847d-60a5f7fbf357](https://user-images.githubusercontent.com/15131169/34082957-c465004c-e31c-11e7-9d3d-8fd1b55ddf81.png)

**Comment by selinad** [comment]
That's really strange -- that was working before....we even tested at the same time....

on the other hand, we were logged in as different users....

**Comment by jimmyzhen** [comment]
I probably broke something. Again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by selinad** [comment]
@jimmyzhen I'll test some more tonight so we can parse it out.  It's very complicated and you are doing a fantastic job.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Yes, the bug appears to be present when it's the same user but as a member of different Affiliations. And it appears to be only affecting the Group evidence **Edit** link in the Curation Palette.

I have just addressed the issue and updated the instance. Please try again. And thank you for catching the 🐛 !

**Comment by selinad** [comment]
@jimmyzhen it's possible you just haven't had time to address, but adding in case -- still spillover on dashboard:
![image](https://user-images.githubusercontent.com/11320314/34129461-10d809ba-e3f9-11e7-91d8-f5c67fc08bda.png)

**Comment by selinad** [comment]
@jimmyzhen for Case-Control that Matt had scored as 3, when I go to View I get this when we are curating as part of same Affiliation:

![image](https://user-images.githubusercontent.com/11320314/34129856-900c8372-e3fa-11e7-8b06-39867d4b0f71.png)

When I instead go to Edit, all is good (I can edit and it saves ).  However, if I change the score and then go View, I get this (i.e. no scoring option):

![image](https://user-images.githubusercontent.com/11320314/34129921-d48726b0-e3fa-11e7-947a-8a4663de3fc4.png)

**Comment by selinad** [comment]
@jimmyzhen unfortunately, there is still a problem with interpretations -- this is the same variant with me curating as myself and as part of BG1.  In the dashboard for myself I can get straight into the interpretation for both....

![image](https://user-images.githubusercontent.com/11320314/34130174-b657b816-e3fb-11e7-9ef3-209d49910531.png)

**Comment by selinad** [comment]
@wrightmw instead of it saying "Affiliation: None" do you think we should repeat the wording found in the pull-down 

Affiliation: No Affiliation (Selina Dwight)

**Comment by wrightmw** [comment]
@selinad Yeah, I agree. Keep it consistent.

**Comment by selinad** [comment]
@jimmyzhen -- here is screenshot of what we talked about.  The "Met" values are not saved on the pull-down and there is something funny about the calculator bar...although maybe it was saved as modified very strong?  That could be it and it's just not displaying on the pull-down:

![image](https://user-images.githubusercontent.com/11320314/34135541-219da3a0-e416-11e7-8887-f433d128707b.png)

**Comment by selinad** [comment]
Hi @jimmyzhen Curate variant in the GCI working well now!

One thing:  Can you make it so "Curator" is the Affiliation name rather than the user who enters it?  When I am looking at the window, it says Selina, but then Matt's same window says Matt....it needs to say BG1 for both of us.

![image](https://user-images.githubusercontent.com/11320314/34135924-48ae9812-e418-11e7-8314-725384ed0a6e.png)

**Comment by jimmyzhen** [comment]
Included in R15 release.
