### ISSUE TITLE
Update current partial Orphanet mappings to full set

### ISSUE THREAD

**Issue by tsneddon** [ClinGen/clincoded#341]
The file we currently use for mapping Orphanet IDs to disease terms is from the Orphanet public download site but this only includes the rare diseases and not the common diseases that are also displayed on their website eg autosomal dominant polycystic kidney disease (ORPHA730).

We need a comprehensive file but this requires signing forms and was requested for by Erin Riggs over a month ago. Orphanet are currently not responding to my repeated new request....

Will reassign this ticket to a developer when I get hold of the new file.

**Comment by tsneddon** [comment]
Dear Tam,

You contacted the Genetic and Rare Diseases Information Center (GARD) asking how to obtain a complete file with our Orpha IDs.  

I have attached a document with information on our new API that includes the Orpha identifiers for all of our diseases.  You will also need the following username and password to access the data.

Username: tsneddon@stanford.edu
Password: n4UttMJa)7GRSb&Sk(9X

If you can let us know more about how you intend to use this information, that will help us document the need for our database.  If you have any questions, please let me know. 

Sincerely,

Michelle Snyder
Information Specialist

[Terms and Conditions of Use_final.docx](https://github.com/ClinGen/clincoded/files/14363/Terms.and.Conditions.of.Use_final.docx)

**Comment by kgliu0101** [comment]
@tsneddon I got an error message. Would you please ensure the user name and password still work.
![rarediseases](https://cloud.githubusercontent.com/assets/9206696/10554733/1b454d0e-741b-11e5-9f0d-18b9ac78d0cf.png)

**Comment by tsneddon** [comment]
I have just emailed Michelle at GARD. Will keep you posted. Thanks for following up on this Kang.

**Comment by kgliu0101** [comment]
@tsneddon You are always quick. Thanks.

**Comment by selinad** [comment]
What's strange is that I think Charlotte said all terms were available via xml, it's just some summaries that are licensed. Is this not the case?  I have a flyer she gave me and I can recheck my notes when I'm in.

**Comment by tsneddon** [comment]
@selinad - Kang can let you know what he has access to but I was under the impression only the ORDO file of rare diseases was public. I followed up directly with Orphanet on an email that Erin never got an answer to:

Le 06-02-2015 16:05, Riggs, Erin a écrit :
Thanks Charlotte!  Would you mind sending me a copy of the form you referred to on our last call that we would need to fill out if we wanted access to the OrphaNet files?  I'd like to look it over and see what it entails.
 
Thank you!
Erin
 
Erin Rooney Riggs, MS, CGC

**Comment by tsneddon** [comment]
@kgliu0101 - please try the login again.

Dear Tam,

Please try again using the login details I sent earlier. I checked our system and they should work for you now. If you have any other problems, let me know and I will address them right away. We just recently launched our API so we may have a few bugs to work out.

Also, thank you for sending details on how you will be using our API. It is very helpful information for us.

Best,
Michelle

**Comment by kgliu0101** [comment]
Download 6649 diseases from the site. Sample as:
![gard_disease](https://cloud.githubusercontent.com/assets/9206696/10650059/456e69c8-77fc-11e5-84c4-adb27d075094.png)

**Comment by tsneddon** [comment]
Hi Tam,

The Orpha IDs are displayed in the detailed information for individual diseases:
https://api.rarediseases.info.nih.gov/api/diseases/<disease_id> 

For example, if you access the data for 15q11.2 microdeletion, which is disease id 10525, you will see the identifier for Orphanet is 261183.

Michelle

**Comment by kgliu0101** [comment]
That means each disease has different url. There are total 6880 diseases in GARD. To get data for each, we have to run the API 6880 times. In addition, in her sample (disease id 10525), there are 2 identifiers and none of them is shown with a mark related to Orphanet.
![gard_disease](https://cloud.githubusercontent.com/assets/9206696/10675462/20c0d55c-78b5-11e5-9dac-18884ca5578b.png)

**Comment by tsneddon** [comment]
Urgh, thanks for checking @kgliu0101 . I'll keep at Michelle. @selinad - can you follow up with Charlotte to see if there is an easier way to get the data?

**Comment by selinad** [comment]
done.

**Comment by kgliu0101** [comment]
Since it is still not sure where we can get those data, I suggest move this ticket to R3.

**Comment by selinad** [comment]
These data are not available - common terms cannot be downloaded, and they are reluctant to give out as they may obsolete them - we will need to work toward another ontology solution

**Comment by wrightmw** [comment]
We now use MonDo for mapping disease terms. Closing this ticket.
