### ISSUE TITLE
Expand delete functionality

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#494]
After discussion and further testing, the need to expand the delete functionality has been determined:

* Make all children of the deleted item also have a status of 'deleted' :white_check_mark: 
  * Involves disassociating all children from their parent to avoid audit errors :white_check_mark: 
  * History should track these child deletions, but not necessarily show them in the user's history (history tracking needs to be able to differentiate between history items to show in user's history or just track in the background) :white_check_mark: 
  * History item for deleting item with children should be different from that of deleting item with no children (for same type of item) :white_check_mark: 
  * Would make children of deleted items inaccessible to non-admins :white_check_mark: 
* Show the list of children items to be deleted in the delete confirmation modal :white_check_mark: 
* Make deleted items not show up in search for curators (currently deleted items are inaccessible, but show up in search results) :white_check_mark:

**Comment by mrmin123** [comment]
Delete group modal w/ children listed:
![image](https://cloud.githubusercontent.com/assets/4326866/11854381/6e7bd2d8-a3f8-11e5-8fbc-0eba1df43353.png)

Delete family modal w/ children listed:
![image](https://cloud.githubusercontent.com/assets/4326866/11854390/7a831a14-a3f8-11e5-85ac-c943e2092836.png)

Delete modal for anything else remains unchanged:
![image](https://cloud.githubusercontent.com/assets/4326866/11854400/88d42162-a3f8-11e5-9eab-0d19eccc2910.png)

**Comment by mrmin123** [comment]
Optionally, showing the item to be deleted in the tree:

![image](https://cloud.githubusercontent.com/assets/4326866/11854542/618de5e2-a3f9-11e5-9a9a-5c4b795b21a0.png)

![image](https://cloud.githubusercontent.com/assets/4326866/11854549/681377ce-a3f9-11e5-9e8e-99832165430b.png)

**Comment by selinad** [comment]
Excellent, @mrmin123.  I prefer the option of showing the item to be deleted in the tree.  Would the links go to the view page (for the associated items)?

**Comment by mrmin123** [comment]
@selinad Yes, they go to the associated items' view pages. Did you want them to go somewhere else?

**Comment by selinad** [comment]
nope - that sounds perfect - was just checking.  Thanks for doing this!

Selina

**Comment by mrmin123** [comment]
@kilodalton @kgliu0101 @forresttanaka I dug around the audit scripts a bit and found a potential alternate solution that retains links within the deleted item and its children without removing pre-existing checks in the audit scripts and still being able to utilize the `status` field in the objects for filtering and view/edit permission control.

The proposal is to ADD an audit rule so that the status mismatch error does not fire when both a child's `status` and `active` fields are set to `deleted` and `false`, respectively. This means that when an object (and its children) are being deleted, it and its children's `status` and `active` fields will be set to `deleted` and `false` respectively, but the links between them will be conserved without firing any audit errors. The link to the item being deleted will still be removed from its parent, and the history object created for the deletion of the target item will retain the `@id` pointing to the original parent as discussed this morning (this means that even if the delete has to be undone manually, it's only one link that has to be manually created). Reliance on the `status` field is maintained so that view/edit permissions (admin vs curators) are retained. Secondary reliance on the `active` field (not currently used anywhere else) adds a secondary check for the audit so that its usual status mismatch checks exists, but is overlooked for items specifically set as both deleted AND inactive, which should theoretically be only done by the delete action.

I think this is the most ideal solution I could come up with given the constraints, but does it sound reasonable to anyone else or am I overlooking any major pitfalls/issues?

**Comment by mrmin123** [comment]
@selinad Do you think it would be OK to just display the 'Are you sure you want to delete this item?' on the confirm delete modal for Groups and Families if they don't have any associated Families/Individuals? Or maybe something like 'Are you sure you want to delete this item? (No associated Families/Individuals)'? It looks a bit weird when attempting to delete a Group/Family with no child objects and it just shows an empty tree, with a message saying that its children will be deleted...:

![image](https://cloud.githubusercontent.com/assets/4326866/11905181/a623dffa-a579-11e5-8e80-cd304574c51c.png)

**Comment by selinad** [comment]
Thanks, @mrmin123  - good question. 
I think your text  'Are you sure you want to delete this item? (No associated Families/Individuals)'? is best.

Small point - on all deletes, could we use the text "....sure you want..." instead of "...sure you would like...?"  It sounds a little more ominous ;-), which makes sense for delete.

**Comment by selinad** [comment]
One more thing re the Warning:

Right now:
Warning: Delete this Family will also delete the following associated individuals

Could you say
Warning: Deleting this Family will also delete any associated individuals (see below)

(and same for Group)

Could No associated Family go in tree, or is that programatically complex?

**Comment by mrmin123** [comment]
@selinad You don't want the associated Families to show in the tree for Groups? Just the individuals?

**Comment by selinad** [comment]
Sorry - I've probably confused you - will come find you after this call.  Basically, was just wondering if we could say No Associated Families and No Associated Individuals in the tree view (e.g. show the negative results in tree view)

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/11906351/9a758f30-a580-11e5-8928-ba8a2338943d.png)
![image](https://cloud.githubusercontent.com/assets/4326866/11906368/c4236b86-a580-11e5-8d1c-4e659402c50d.png)
![image](https://cloud.githubusercontent.com/assets/4326866/11906358/a70c616a-a580-11e5-9aeb-6eabde196db1.png)

**Comment by mrmin123** [comment]
Progress is on the [494_expand_delete_alt](https://github.com/ClinGen/clincoded/tree/494_expand_delete_alt) branch. All items in ticket have been addressed, including #519, but not spinning up an instance for testing yet since it's the last day before the holidays.

Testing to be done on instances:
* Confirm update to history schema does not cause issues with production data
  1. spin up instance w/ production data and check for upgrade failures/schema errors
* Make sure delete function is working properly
  1. Create Group/Family/Individual/Experimental Data objects of all kinds, including nested ones
  2. Confirm that the delete modal shows the correct text + children tree
  3. Confirm that performing the delete function forwards you to curation central and the target item + any associated children are also removed
  4. Confirm above step in Safari!! (#519)
  5. Check that the correct relevant history text is displayed on the dashboard
  6. Using the direct URLs to the deleted items, check their JSON objects to make sure that their `status` and `active` fields are set to `deleted` and `false`, respectively. Also check if there are any `audit` warnings (especially important for nested objects!!!)
* Confirm permissions are working properly
  1. On admin account, confirm that deleted items both by yourself and others are both searchable and viewable
  2. On curator (non-admin) account, confirm that deleted items both by yourself and others are both NOT searchable and NOT viewable

**Comment by selinad** [comment]
HI @mrmin123 - fantastic!

Only 2 minor points:
* could the second indent for an arrow be a little further indented? (e.g. "no associated individuals" under family1 for the first image
* I'm a little worried that the "Are you sure you want to delete this item?"  is closer to the sub-items than the main ones - maybe it should go above the tree?

**Comment by mrmin123** [comment]
@selinad Something more like this?:

![image](https://cloud.githubusercontent.com/assets/4326866/12097227/54021e86-b2cf-11e5-8a07-23a4402953f9.png)

**Comment by selinad** [comment]
The indent looks good - thanks!

Slight wording change:

"(see below)" -> "(see any Families or Individuals associated with the Group under its name, bolded below)"

For a Family, it would just say "(see any Individuals associated with the Family under its name, bolded below)"

Instead of "Are you sure you want to delete this item?", replace "item" with "Group" or "Family" - e.g.:

"Are you sure you want to delete this Group?"

Let me know if this works....

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/12100125/c5454566-b2e1-11e5-8000-47c7b5159b9e.png)

![image](https://cloud.githubusercontent.com/assets/4326866/12100131/d2a1be42-b2e1-11e5-8df0-a0df3c6aaba8.png)

**Comment by selinad** [comment]
Looks good - will wait to see what @wrightmw thinks.

One thing - can you separate "Are you sure want to delete this item?" from the text before it - i.e. make it its own paragraph, separated by blank line.

thx!
Selina

**Comment by mrmin123** [comment]
On its own line:

![image](https://cloud.githubusercontent.com/assets/4326866/12131354/8cc5174e-b3c6-11e5-93c0-d5ce971da3f4.png)

**Comment by selinad** [comment]
I like it.  @wrightmw can confirm.

**Comment by wrightmw** [comment]
Wow... @mrmin123 this is looking great. I agree with the tweaks suggested by @selinad . The instructions now look pretty clear to me. The two of you have done a great job on this.

**Comment by mrmin123** [comment]
Thanks @wrightmw. I spun up an instance to test the functionality: http://494-expand-delete-alt-95ca753-minchoi.instance.clinicalgenome.org/

Things to test:
1. Create GDM
2. Create all sorts of different Group, Family, Individual, Experimental Data combos (w/ children, w/o children, different parents, etc)
3. Try to delete them. Confirm that modal display is correct, and deletions occur properly.
  * Do above as both Admin and Curator
4. Confirm that the history items properly reflect delete operations
5. If logged in as Admin, confirm that you can still see deleted items in search/indexes
6. If logged in as Curator, confirm that you CANNOT see deleted items in search/indexes

**Comment by selinad** [comment]
Noticed this while testing - should I make separate ticket? (text is off button):

![screen shot 2016-01-05 at 5 31 50 pm](https://cloud.githubusercontent.com/assets/11320314/12132605/4dc4b99e-b3d2-11e5-9fbd-4cccad2e84a8.png)

**Comment by selinad** [comment]
Am not sure about item 6 (how to test) and can't comment on 5, but all others look right and function well!

**Comment by wrightmw** [comment]
Ditto. That is it all looks good, however I can't log in as Admin to do test item 5 and I'm not sure what you mean for item 6?

**Comment by mrmin123** [comment]
@selinad What browser is this in?

**Comment by selinad** [comment]
Chrome

**Comment by mrmin123** [comment]
For item 5 and 6, I meant that the deleted items should not show up on this page: http://494-expand-delete-alt-95ca753-minchoi.instance.clinicalgenome.org/search/ unless you are logged in as an admin. For the record, your default e-mails (selinad@ and wrightmw@) should be set as Admin accounts, and your secondaries e-mails (ssdwight@, selina.dwight@, mathew.wright@) should be set as Curator accounts.

**Comment by mrmin123** [comment]
@selinad that visual bug with the button text flowing out should be fixed on this branch: http://494-expand-delete-alt-c65443d-minchoi.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Looks good - thanks!

<img width="563" alt="screen shot 2016-01-06 at 11 05 42 am" src="https://cloud.githubusercontent.com/assets/11320314/12151743/7fcd7cee-b465-11e5-86b1-fc3c7055481e.png">

**Comment by wrightmw** [comment]
Ok, I have tested doing deletions with your new instance using both my admin and non-admin accounts. I can now confirm that when logged in as admin, I can still see deleted items in search/indexes but if am logged in as non-admin then I cannot see deleted items in search/indexes.

**Comment by mrmin123** [comment]
@wrightmw Great, much thanks.

**Comment by selinad** [comment]
Looks good in QA1

**Comment by wrightmw** [comment]
You just beat me to it @selinad ... looks good!

**Comment by selinad** [comment]
You get to move it to release ready :-)

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
