### ISSUE TITLE
Explanation text for HPO terms incorrect (HP_ instead of HP:)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#562]
In the experimental evidence, we have the following description (HP_....), but HP: is required as prefix in box:

![screen shot 2016-01-28 at 5 45 25 pm](https://cloud.githubusercontent.com/assets/11320314/12664810/9f105656-c5e7-11e5-89bb-8f0635251bbe.png)

Need to change text to be HP: ... on following pages:
* Bioch Function B
* Model Systems (both pull-down types, eg. animal and engineered equivalent)
* Rescue (both pull-downs, e.g. engineered equivalent and patient)
* Group page
* Family page
* Individual page

**Comment by kilodalton** [comment]
I believe the changes are only in  `src/clincoded/static/components/curator.js` in a few places.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Per discussion in the meeting, the reported bug has been addressed in recent changes committed to the `dev` branch. And thus we just need to spin up an EC2 instance with the latest version of the `dev` branch for the curators to verify the fix.

The following is the `dev` branch instance for curators' review:
https://562-jz-dev-fe04cd0-jzhen.demo.clinicalgenome.org

Please let us know if there are any questions. Thank you.

**Comment by selinad** [comment]
Hi @jimmyzhen I may be confused as I saw this when I brought up the Family page (underscore still present):
![screen shot 2016-02-02 at 11 35 21 am](https://cloud.githubusercontent.com/assets/11320314/12761767/270580f6-c9a1-11e5-9dc9-a450305c8ba0.png)

I also see that the way we handle the instructions is different for G and F....

**Comment by kilodalton** [comment]
@jimmyzhen The bug we needed info about reproducing was on a different ticket. Not this one.

**Comment by jimmyzhen** [comment]
@selinad, @kilodalton, my sincere apologies!

It should be for https://github.com/ClinGen/clincoded/issues/533, correct?

**Comment by selinad** [comment]
@jimmyzhen no worries!  It's confusing.

The bug is #533; this one is fixing incorrect text in the locations listed above.

**Comment by selinad** [comment]
Should I use the URL you gave to test the bug fix?

**Comment by jimmyzhen** [comment]
@selinad I terminated that instance because there is a bug in the current version of the `dev` branch (which we found out today). A fix had been submitted, and if it gets merged into the dev branch, I will spin up a new instance including the fix. I will notify you again when a URL becomes available for testing. Thanks.

cc @kilodalton

**Comment by kilodalton** [comment]
@jimmyzhen The fix for #577/PR #578 has been merged

**Comment by jimmyzhen** [comment]
@kilodalton, thank you!

**Comment by jimmyzhen** [comment]
The requested text change has been implemented on the site on my local machine:
![image](https://cloud.githubusercontent.com/assets/6956310/12799283/d33da8e4-ca82-11e5-8aa4-512b6c549f04.png)

**Comment by selinad** [comment]
Great!  Thanks, @jimmyzhen!

It occurs several places other than Family (listed in issue) - just double-checking that those also get updated?

-S

**Comment by jimmyzhen** [comment]
@selinad, please review the requested text changes at:
https://562-568-569-jz-text-change-a125269-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Super - all look great! thx @jimmyzhen !

**Comment by selinad** [comment]
All good  - Matt: test pages should include all following:
Bioch Function B
Model Systems (both pull-down types, eg. animal and engineered equivalent)
Rescue (both pull-downs, e.g. engineered equivalent and patient)
Group page
Family page
Individual page

**Comment by wrightmw** [comment]
All fine and dandy!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
